import moduleTypes from '../types'

const actionMutationTypes = {
  ADD_PLAYER_BETSLIP: 'ADD_PLAYER_BETSLIP',
  UPDATE_SELECTED_THEME: 'UPDATE_SELECTED_THEME',
  TOGGLE_SELECTED_THEME_TYPE: 'TOGGLE_SELECTED_THEME_TYPE',
  UPDATE_SELECTED_THEME_TYPE: 'UPDATE_SELECTED_THEME_TYPE',
  RESET_TO_DEFAULT_THEME: 'RESET_TO_DEFAULT_THEME',
  DISABLE_LOADING_OVERLAY: 'DISABLE_LOADING_OVERLAY',
  RESET_LIVE_DRAW: 'RESET_LIVE_DRAW',
  ENABLE_LOADING_OVERLAY: 'ENABLE_LOADING_OVERLAY',
  TOGGLE_NEXT_DRAW_LOADING_OVERLAY_ENABLE: 'TOGGLE_NEXT_DRAW_LOADING_OVERLAY_ENABLE',
  TOGGLE_NEXT_DRAW_LOADING_OVERLAY_DISABLE: 'TOGGLE_NEXT_DRAW_LOADING_OVERLAY_DISABLE',
  TOGGLE_IFRAME_LOADED_ENABLE: 'TOGGLE_IFRAME_LOADED_ENABLE',
  TOGGLE_IFRAME_LOADED_DISABLE: 'TOGGLE_IFRAME_LOADED_DISABLE',
  ENABLE_KINO_GAME_INACTIVE: 'ENABLE_KINO_GAME_INACTIVE',
  DISABLE_KINO_GAME_INACTIVE: 'DISABLE_KINO_GAME_INACTIVE',
  UPDATE_OLISOFT_DRAW_ID: 'UPDATE_OLISOFT_DRAW_ID',
  UPDATE_INTRALOT_DRAW_ID: 'UPDATE_INTRALOT_DRAW_ID',
  ENABLE_ERROR_STATE: 'ENABLE_ERROR_STATE',
  DISABLE_ERROR_STATE: 'DISABLE_ERROR_STATE',
};

const getterTypes = {
  GET_THEMES_SIMPLE: 'GET_THEMES_SIMPLE',
  GET_THEMES_SIDEBETS: 'GET_THEMES_SIDEBETS',
  GET_THEMES: 'GET_THEMES',
  GET_DEFAULT_THEME: 'GET_DEFAULT_THEME',
  GET_SELECTED_THEME: 'GET_SELECTED_THEME',
  GET_SELECTED_THEME_TYPE: 'GET_SELECTED_THEME_TYPE',
  GET_IS_LOADING_OVERLAY_ENABLED: 'GET_IS_LOADING_OVERLAY_ENABLED',
  GET_IS_NEXT_DRAW_LOADING_OVERLAY_ENABLED: 'GET_IS_NEXT_DRAW_LOADING_OVERLAY_ENABLED',
  GET_IS_IFRAME_LOADED: 'GET_IS_IFRAME_LOADED',
  GET_IS_KINO_GAME_INACTIVE: 'GET_IS_KINO_GAME_INACTIVE',
  GET_OLISOFT_DRAW_ID: 'GET_OLISOFT_DRAW_ID',
  GET_INTRALOT_DRAW_ID: 'GET_INTRALOT_DRAW_ID',
  GET_HAS_MATCHING_DRAW_IDS: 'GET_HAS_MATCHING_DRAW_IDS',
  GET_ERROR_STATE: 'GET_ERROR_STATE',
  GET_IS_INVALID_DRAW_ID: 'GET_IS_INVALID_DRAW_ID',
  GET_SHOULD_DISPLAY_ERROR: 'GET_SHOULD_DISPLAY_ERROR',
};

const namespaceMapper = {
  RESET_TO_DEFAULT_THEME: `${moduleTypes.LIVE_DRAW_MODULE}/${actionMutationTypes.RESET_TO_DEFAULT_THEME}`,
  DISABLE_LOADING_OVERLAY: `${moduleTypes.LIVE_DRAW_MODULE}/${actionMutationTypes.DISABLE_LOADING_OVERLAY}`,
  RESET_LIVE_DRAW: `${moduleTypes.LIVE_DRAW_MODULE}/${actionMutationTypes.RESET_LIVE_DRAW}`,
  UPDATE_INTRALOT_DRAW_ID: `${moduleTypes.LIVE_DRAW_MODULE}/${actionMutationTypes.UPDATE_INTRALOT_DRAW_ID}`,
};

const types = {
  mutations: { ...actionMutationTypes },
  actions: { ...actionMutationTypes },
  getters: { ...getterTypes },
  namespaceMapper: { ...namespaceMapper }
};

export default types;
