import moduleTypes from '../types';

const mutationTypes = {
  TOGGLE_NUMBER: 'TOGGLE_NUMBER',
  ADD_BET_AREA: 'ADD_BET_AREA',
  CHANGE_ACTIVE_BET_AREA: 'CHANGE_ACTIVE_BET_AREA',
  TOGGLE_QUICK_PICK: 'TOGGLE_QUICK_PICK',
  DELETE_BET_AREA: 'DELETE_BET_AREA',
  CLEAR_ACTIVE_BET_AREA: 'CLEAR_ACTIVE_BET_AREA',
  SET_KINO_BONUS_VALUE: 'SET_KINO_BONUS_VALUE',
  SET_KINO_CLOSE_2_WIN_VALUE: 'SET_KINO_CLOSE_2_WIN_VALUE',
  TOGGLE_MULTIPLIER: 'TOGGLE_MULTIPLIER',
  SET_ODD_EVEN: 'SET_ODD_EVEN',
  RESET_ODD_EVEN: 'RESET_ODD_EVEN',
  SET_COLUMNS: 'SET_COLUMNS',
  RESET_COLUMNS: 'RESET_COLUMNS',
  QUICK_PICK: 'QUICK_PICK',
  CLEAR_BETSLIP: 'CLEAR_BETSLIP',
  SET_BETSLIP: 'SET_BETSLIP',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
  RESET_BETSLIP: 'RESET_BETSLIP',
  SET_READY_BETSLIPS_NUMBERS: 'SET_READY_BETSLIPS_NUMBERS',
};

const actionTypes = {
  TOGGLE_NUMBER: 'TOGGLE_NUMBER',
  ADD_BET_AREA: 'ADD_BET_AREA',
  DELETE_BET_AREA: 'DELETE_BET_AREA',
  CHANGE_ACTIVE_BET_AREA: 'CHANGE_ACTIVE_BET_AREA',
  TOGGLE_QUICK_PICK: 'TOGGLE_QUICK_PICK',
  CLEAR_ACTIVE_BET_AREA: 'CLEAR_ACTIVE_BET_AREA',
  SET_KINO_BONUS_VALUE: 'SET_KINO_BONUS_VALUE',
  SET_KINO_CLOSE_2_WIN_VALUE: 'SET_KINO_CLOSE_2_WIN_VALUE',
  TOGGLE_MULTIPLIER: 'TOGGLE_MULTIPLIER',
  SET_ODD_EVEN: 'SET_ODD_EVEN',
  RESET_ODD_EVEN: 'RESET_ODD_EVEN',
  SET_COLUMNS: 'SET_COLUMNS',
  RESET_COLUMNS: 'RESET_COLUMNS',
  QUICK_PICK: 'QUICK_PICK',
  CLEAR_BETSLIP: 'CLEAR_BETSLIP',
  SET_BETSLIP: 'SET_BETSLIP',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
  RESET_BETSLIP: 'RESET_BETSLIP',
  SET_READY_BETSLIPS_NUMBERS: 'SET_READY_BETSLIPS_NUMBERS',
};

const getterTypes = {
  GET_ACTIVE_BET_AREA: 'GET_ACTIVE_BET_AREA',
  GET_BETSLIP_COST: 'GET_BETSLIP_COST',
  GET_CONSECUTIVE_DRAWS: 'GET_CONSECUTIVE_DRAWS',
  GET_READY_BETSLIPS_NUMBERS: 'GET_READY_BETSLIPS_NUMBERS',
};

const state = {
  BETSLIP: 'betslip',
  ACTIVE_AREA_INDEX: 'activeAreaIndex',
  READY_BETSLIPS_NUMBERS: 'readyBetslipsNumbers',
};

const namespaceMapper = {
  BETSLIP_COST: `${moduleTypes.KINO_GAME_STORE_MODULE}/${getterTypes.GET_BETSLIP_COST}`,
  GET_CONSECUTIVE_DRAWS: `${moduleTypes.KINO_GAME_STORE_MODULE}/${getterTypes.GET_CONSECUTIVE_DRAWS}`,
  SET_CONSECUTIVE_DRAWS: `${moduleTypes.KINO_GAME_STORE_MODULE}/${actionTypes.SET_CONSECUTIVE_DRAWS}`,
  GET_READY_BETSLIPS_NUMBERS: `${moduleTypes.KINO_GAME_STORE_MODULE}/${getterTypes.GET_READY_BETSLIPS_NUMBERS}`,
  SET_READY_BETSLIPS_NUMBERS: `${moduleTypes.KINO_GAME_STORE_MODULE}/${actionTypes.SET_READY_BETSLIPS_NUMBERS}`,
};

const types = {
  mutations: { ...mutationTypes },
  actions: { ...actionTypes },
  getters: { ...getterTypes },
  namespaceMapper: { ...namespaceMapper },
  state,
};

export default types;
