export const HAL_INITIALIZED_EVENT_TYPE = 'HAL_INITIALIZED';
export const LOAD_CONFIGURATION = 'LOAD_CONFIGURATION';
export const TERMINAL_NAME_EVENT_TYPE = 'TERMINAL_NAME';
export const PRINTER_STATUS_EVENT_TYPE = 'PRINTER_STATUS';
export const BCR_STATUS_EVENT_TYPE = 'BCR_STATUS';
export const PRINT_EVENT_TYPE = 'PRINT';
export const SCAN_VOUCHER_EVENT_TYPE = 'SCAN_VOUCHER';
export const SCAN_PROMOTION_VOUCHER_EVENT_TYPE = 'SCAN_PROMOTION_VOUCHER_EVENT_TYPE';
export const SCAN_SPORTS_VOUCHER_EVENT_TYPE = 'SCAN_SPORTS_VOUCHER';
export const SCAN_SPORTS_TICKET_EVENT_TYPE = 'SCAN_SPORTS_TICKET';
export const SCAN_OPAP_BET_CARD_EVENT_TYPE = 'SCAN_OPAP_BETCARD';
export const SCAN_INVALID_BARCODE_EVENT_TYPE = 'SCAN_INVALID_BARCODE';
export const GET_WAGER_EVENT_TYPE = 'GET_WAGER';
export const FIND_WINNINGS_EVENT_TYPE = 'FIND_WINNINGS';
export const SWITCH_APPLICATION = 'SWITCH_APP';
export const SWITCH_APPLICATION_ACK = 'ACK';
export const SWITCH_APPLICATION_NACK = 'NACK';
export const BARCODE_READER_STATUS_CHANGE = 'BCR_STATUS_CHANGE';
export const APP_VERSION = 'APP_VERSION';
export const SEND_REQUEST = 'REQUEST';
export const SERVICE_STATUS_CHECK = 'SERVICE_STATUS_CHECK';
export const REQUEST_ISECURE_HASH = 'REQUEST_ISECURE_HASH';
export const REQUEST_CRC = 'REQUEST_CRC';
export const OLISOFT_IFRAME_EVENT = 'OLISOFT_IFRAME_EVENT';
export const LIVE_DRAW_IFRAME_LOAD_FAILED = 'LIVE_DRAW_IFRAME_LOAD_FAILED';
export const WINDOW_SHOWN = 'WINDOW_SHOWN';
export const RENDERER_READY = 'RENDERER_READY';
export const LOG_FROM_RENDERER = 'LOG_FROM_RENDERER';
export const GET_ENV_SYNC = 'GET_ENV_SYNC';

export function prepareEventHandlerObject(eventType, logic) {
  if (typeof eventType === 'undefined' || eventType === null) {
    throw new Error('EventHandler obj can not be initialized!');
  }
  return {
    eventType,
    logic,
  };
}

export default {
  HAL_INITIALIZED_EVENT_TYPE,
  LOAD_CONFIGURATION,
  TERMINAL_NAME_EVENT_TYPE,
  PRINTER_STATUS_EVENT_TYPE,
  BCR_STATUS_EVENT_TYPE,
  PRINT_EVENT_TYPE,
  SCAN_VOUCHER_EVENT_TYPE,
  SCAN_PROMOTION_VOUCHER_EVENT_TYPE,
  SCAN_SPORTS_VOUCHER_EVENT_TYPE,
  SCAN_SPORTS_TICKET_EVENT_TYPE,
  SCAN_OPAP_BET_CARD_EVENT_TYPE,
  SCAN_INVALID_BARCODE_EVENT_TYPE,
  GET_WAGER_EVENT_TYPE,
  FIND_WINNINGS_EVENT_TYPE,
  SWITCH_APPLICATION,
  SWITCH_APPLICATION_ACK,
  SWITCH_APPLICATION_NACK,
  BARCODE_READER_STATUS_CHANGE,
  APP_VERSION,
  SEND_REQUEST,
  SERVICE_STATUS_CHECK,
  REQUEST_ISECURE_HASH,
  REQUEST_CRC,
  OLISOFT_IFRAME_EVENT,
  LIVE_DRAW_IFRAME_LOAD_FAILED,
  WINDOW_SHOWN,
  RENDERER_READY,
  LOG_FROM_RENDERER,
  GET_ENV_SYNC,
  prepareEventHandlerObject,
};
