import moduleTypes from '../types/types';

const mutationTypes = {
  SET_BETSLIP: 'SET_BETSLIP',
  SET_SELECTION: 'SET_SELECTION',
  SET_MULTIPLIER: 'SET_MULTIPLIER',
  QUICK_PICK: 'QUICK_PICK',
  SET_BOARD_BETTYPE: 'SET_BOARD_BETTYPE',
  RESET_BETSLIP: 'RESET_BETSLIP',
  SET_STATISTICS_SELECTION: 'SET_STATISTICS_SELECTION',
  SET_STATISTICS: 'SET_STATISTICS',
  RESET_STATISTICS: 'RESET_STATISTICS',
  CLEAR_SELECTED_BOARD: 'CLEAR_SELECTED_BOARD',
  ADD_BOARD: 'ADD_BOARD',
  REMOVE_BOARD: 'REMOVE_BOARD',
  SET_SELECTED_BOARD_INDEX: 'SET_SELECTED_BOARD_INDEX',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
};

const actionTypes = {
  SET_BETSLIP: 'SET_BETSLIP',
  SET_SELECTION: 'SET_SELECTION',
  SET_MULTIPLIER: 'SET_MULTIPLIER',
  QUICK_PICK: 'QUICK_PICK',
  SET_BOARD_BETTYPE: 'SET_BOARD_BETTYPE',
  RESET_BETSLIP: 'RESET_BETSLIP',
  SET_STATISTICS_SELECTION: 'SET_STATISTICS_SELECTION',
  GET_STATISTICS: 'GET_STATISTICS',
  CLEAR_SELECTED_BOARD: 'CLEAR_SELECTED_BOARD',
  ADD_BOARD: 'ADD_BOARD',
  REMOVE_BOARD: 'REMOVE_BOARD',
  SET_SELECTED_BOARD_INDEX: 'SET_SELECTED_BOARD_INDEX',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
};

const getterTypes = {
  GET_BETSLIP: 'GET_BETSLIP',
  GET_SELECTED_BOARD_INDEX: 'GET_SELECTED_BOARD_INDEX',
  GET_SELECTED_BOARD: 'GET_SELECTED_BOARD',
  GET_CONSECUTIVE_DRAWS: 'GET_CONSECUTIVE_DRAWS',
  GET_BOARD_COST: 'GET_BOARD_COST',
  GET_BETSLIP_COST: 'GET_BETSLIP_COST',
  GET_IS_BETSLIP_VALID: 'GET_IS_BETSLIP_VALID',
  GET_IS_BETSLIP_EMPTY: 'GET_IS_BETSLIP_EMPTY',
  GET_STATISTICS: 'GET_STATISTICS',
  GET_STATISTICS_SELECTION: 'GET_STATISTICS_SELECTION',
};

const namespaceMapper = {
  BETSLIP_COST: `${moduleTypes.FIREBLAZE_GAME_STORE_MODULE}/${getterTypes.GET_BETSLIP_COST}`,
  GET_CONSECUTIVE_DRAWS: `${moduleTypes.FIREBLAZE_GAME_STORE_MODULE}/${getterTypes.GET_CONSECUTIVE_DRAWS}`,
  SET_CONSECUTIVE_DRAWS: `${moduleTypes.FIREBLAZE_GAME_STORE_MODULE}/${actionTypes.SET_CONSECUTIVE_DRAWS}`,
};

const types = {
  mutations: { ...mutationTypes },
  actions: { ...actionTypes },
  getters: { ...getterTypes },
  namespaceMapper: { ...namespaceMapper },
};

export default types;
