import moduleTypes from '../types/types';

const MODULE_NAME = moduleTypes.EUROJACKPOT_GAME_STORE_MODULE;

const mutations = {
  SET_BETSLIP: 'SET_BETSLIP',
  SET_SELECTED_BOARD_INDEX: 'SET_SELECTED_BOARD_INDEX',
  SET_BETSLIP_CONSECUTIVE_DRAWS: 'SET_BETSLIP_CONSECUTIVE_DRAWS',
  ADD_BOARD: 'ADD_BOARD',
  REMOVE_BOARD: 'REMOVE_BOARD',
  CLEAR_SELECTED_BOARD: 'CLEAR_SELECTED_BOARD',
  TOGGLE_QUICK_PICK: 'TOGGLE_QUICK_PICK',
  SET_MAIN_SELECTION: 'SET_MAIN_SELECTION',
  SET_EURO_SELECTION: 'SET_EURO_SELECTION',
  SET_SYSTEM: 'SET_SYSTEM',
  RESET_BETSLIP: 'RESET_BETSLIP',
  SET_ACTIVE_DRAW_API_TIMEOUT: 'SET_ACTIVE_DRAW_API_TIMEOUT',
  RESET_ACTIVE_DRAW_API_TIMEOUT: 'RESET_ACTIVE_DRAW_API_TIMEOUT',
  SET_SALES_OPEN: 'SET_SALES_OPEN',
  SET_SALES_CLOSED: 'SET_SALES_CLOSED',
  SET_STATISTICS: 'SET_STATISTICS',
  RESET_STATISTICS: 'RESET_STATISTICS',
  SET_STATISTICS_SELECTION: 'SET_STATISTICS_SELECTION',
  SET_IS_ACTIVE_DRAW_EXTRA: 'SET_IS_ACTIVE_DRAW_EXTRA',
};

const actions = {
  SET_BETSLIP: 'SET_BETSLIP',
  SET_SELECTED_BOARD_INDEX: 'SET_SELECTED_BOARD_INDEX',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
  ADD_BOARD: 'ADD_BOARD',
  REMOVE_BOARD: 'REMOVE_BOARD',
  CLEAR_SELECTED_BOARD: 'CLEAR_SELECTED_BOARD',
  TOGGLE_QUICK_PICK: 'TOGGLE_QUICK_PICK',
  SET_MAIN_SELECTION: 'SET_MAIN_SELECTION',
  SET_EURO_SELECTION: 'SET_EURO_SELECTION',
  SET_SYSTEM: 'SET_SYSTEM',
  RESET_BETSLIP: 'RESET_BETSLIP',
  GET_DRAW_INFO: 'GET_DRAW_INFO',
  SET_SALES_OPEN: 'SET_SALES_OPEN',
  SET_SALES_CLOSED: 'SET_SALES_CLOSED',
  CLEAR_TIMER: 'CLEAR_TIMER',
  GET_STATISTICS: 'GET_STATISTICS',
  SET_STATISTICS_SELECTION: 'SET_STATISTICS_SELECTION',
};

const getters = {
  GET_BETSLIP: 'GET_BETSLIP',
  GET_SELECTED_BOARD_INDEX: 'GET_SELECTED_BOARD_INDEX',
  GET_SELECTED_BOARD: 'GET_SELECTED_BOARD',
  GET_BETSLIP_CONSECUTIVE_DRAWS: 'GET_BETSLIP_CONSECUTIVE_DRAWS',
  GET_BOARD_COST: 'GET_BOARD_COST',
  GET_BETSLIP_COST: 'GET_BETSLIP_COST',
  GET_IS_BETSLIP_VALID: 'GET_IS_BETSLIP_VALID',
  GET_IS_BETSLIP_EMPTY: 'GET_IS_BETSLIP_EMPTY',
  GET_DRAW_DAYS: 'GET_DRAW_DAYS',
  GET_ACTIVE_DRAW_TIME: 'GET_ACTIVE_DRAW_TIME',
  GET_SALES_CLOSE_TIME: 'GET_SALES_CLOSE_TIME',
  GET_ACTIVE_DRAW_ID: 'GET_ACTIVE_DRAW_ID',
  GET_JACKPOT_AMOUNT: 'GET_JACKPOT_AMOUNT',
  GET_IS_SALES_OPEN: 'GET_IS_SALES_OPEN',
  GET_IS_SALES_CLOSED: 'GET_IS_SALES_CLOSED',
  GET_STATISTICS: 'GET_STATISTICS',
  GET_STATISTICS_SELECTION: 'GET_STATISTICS_SELECTION',
  GET_IS_ACTIVE_DRAW_EXTRA: 'GET_IS_ACTIVE_DRAW_EXTRA',
};

const namespaceMapper = {
  SET_BETSLIP: `${MODULE_NAME}/${mutations.SET_BETSLIP}`,
  SET_SELECTED_BOARD_INDEX: `${MODULE_NAME}/${mutations.SET_SELECTED_BOARD_INDEX}`,
  SET_CONSECUTIVE_DRAWS: `${MODULE_NAME}/${mutations.SET_BETSLIP_CONSECUTIVE_DRAWS}`,
  ADD_BOARD: `${MODULE_NAME}/${mutations.ADD_BOARD}`,
  REMOVE_BOARD: `${MODULE_NAME}/${mutations.REMOVE_BOARD}`,
  CLEAR_SELECTED_BOARD: `${MODULE_NAME}/${mutations.CLEAR_SELECTED_BOARD}`,
  RESET_BETSLIP: `${MODULE_NAME}/${mutations.RESET_BETSLIP}`,
  ACTION_SET_BETSLIP: `${MODULE_NAME}/${actions.SET_BETSLIP}`,
  ACTION_SET_CONSECUTIVE_DRAWS: `${MODULE_NAME}/${actions.SET_CONSECUTIVE_DRAWS}`,
  ACTION_RESET_BETSLIP: `${MODULE_NAME}/${actions.RESET_BETSLIP}`,
  GET_BETSLIP: `${MODULE_NAME}/${getters.GET_BETSLIP}`,
  GET_CONSECUTIVE_DRAWS: `${MODULE_NAME}/${getters.GET_BETSLIP_CONSECUTIVE_DRAWS}`,
  BETSLIP_COST: `${MODULE_NAME}/${getters.GET_BETSLIP_COST}`,
  GET_IS_BETSLIP_VALID: `${MODULE_NAME}/${getters.GET_IS_BETSLIP_VALID}`,
  GET_IS_BETSLIP_EMPTY: `${MODULE_NAME}/${getters.GET_IS_BETSLIP_EMPTY}`,
  GET_JACKPOT_AMOUNT: `${MODULE_NAME}/${getters.GET_JACKPOT_AMOUNT}`,
  GET_IS_SALES_OPEN: `${MODULE_NAME}/${getters.GET_IS_SALES_OPEN}`,
};

export default {
  mutations,
  actions,
  getters,
  namespaceMapper,
};
