////////////////////////////////////////// Define elements of Eurojackpot App /////////////////////////////////////////////////

module.exports = {
  LobbyHeader: '#ssbt_lobbyHeader',
  LobbyKino: '#lobby-games-kino',
  LobbyPowerspin: '#lobby-games-powerspin-img',
  LobbyEurojackpot: '#lobby-games-eurojackpot-img',
  PowerspinMainMenuBtn: '#ssbt_return_to_lobby',
  EurojackpotClearAllBtn: '#ssbt_base_clear_button_header',
  LobbyHeaderLangSelection: '.ssbt-header-language-selection--black',
  LobbyElBtn: '#ssbt_lang_gr',
  LobbyEnBtn: '#ssbt_lang_en',

  PowerspinClearAllBtn: '#ssbt_base_clear_button_header',
  PowerspinModalAMsgLbl: '#info-modal-title',
  PowerspinModalAMsg: '#info-modal-message',
  PowerspinModalAYesBtn: '#yes-option',
  PowerspinModalANoBtn: '#no-option',

  EurojackpotLogo: '#ssbt_lobby-header-img',
  EurojackpotScanError: '#ssbt_barcode_error',
  EurojackpotMainMenuBtn: '#ssbt_return_to_lobby',
  EurojackpotTC: '#ssbt-header-game-info-terms',
  EurojackpotTCTitle: '#infoTitle',
  EurojackpotTCClose: '#close-info-modal',
  EurojackpotTCOk: '#info-modal-ok',
  EurojackpotTCMessage: '#infoMessage',
  EurojackpotTCScrollbar: '#info > div.vue-scrollbar__wrapper.info-body > div > div:nth-child(2) > div > div',

  EurojackpotHowToPlay: '#ssbt-header-game-info-how-to-play',
  EurojackpotHowToPlayClose: '#help_close_btn',
  EurojackpotHowToPlayModal: '#ssbt-header-game-info-how-to-play',
  EurojackpotCashoutField: '#ssbt_cash_out',
  EurojackpotCashoutLbl: '#ssbt_cash_out',

  EurojackpotBalanceBtn: '.ssbt_header_balance_box__eye-icon',
  EurojackpotBalanceShow: '#ssbt_balance_box',
  EurojackpotBalanceHide: '#ssbt_balance_box',
  EurojackpotRefresh: '#ssbt_balance_refresh',

  EurojackpotClearBtn: '#ejp-play-area-clear-betslip-btn',

  // Random Pick
  EurojackpotWinningsTableNumbers: '.eurojackpot-quickpick__info',
  EurojackpotRandomPickBtn: '#ejp-quickpick-btn',

  // System
  EurojackpotSystemHeaderTitle: '.eurojackpot-systems__header-title',
  EurojackpotSystemHeaderInfo: '.eurojackpot-systems__header-info',
  EurojackpotSystemNumbers: '.eurojackpot-systems__numbers',
  EurojackpotSystemBtn12: '#ejp-system-btn-12',
  EurojackpotSystemBtn13: '#ejp-system-btn-13',
  EurojackpotSystemBtn14: '#ejp-system-btn-14',
  EurojackpotSystemBtn15: '#ejp-system-btn-15',
  EurojackpotSystemBtn23: '#ejp-system-btn-23',
  EurojackpotSystemBtn24: '#ejp-system-btn-24',
  EurojackpotSystemBtn25: '#ejp-system-btn-25',
  EurojackpotSystemBtn34: '#ejp-system-btn-34',
  EurojackpotSystemBtn35: '#ejp-system-btn-35',
  EurojackpotSystemBtn45: '#ejp-system-btn-45',

  EurojackpotSystemBtn12Active: '.eurojackpot-system-button--active',

  // Eurojackpot days
  EurojackpotWrapper: '.euro-jackpot-next-draw__wrapper--europe',
  EurojackpotDays: '.euro-jackpot-next-draw--content',
  // '.euro-jackpot-next-draw--content__title-days',

  // Main numbers 1-50
  EurojackpotChooseMainNumbersLbl:
    '#eurojackpot > div > div.play-area-layout__play-area > div > div > div.eurojackpot-play-area__main > div:nth-child(1) > div.number-selection-layout__header',
  EurojackpotChooseMainNumbers:
    '#eurojackpot > div > div.play-area-layout__play-area > div > div > div.eurojackpot-play-area__main > div:nth-child(1) > div.number-selection-layout__number-wrapper',
  EurojackpotChooseMainNumber1Btn: '#ejp-main-number-btn-1',
  EurojackpotChooseMainNumber2Btn: '#ejp-main-number-btn-2',
  EurojackpotChooseMainNumber3Btn: '#ejp-main-number-btn-3',
  EurojackpotChooseMainNumber4Btn: '#ejp-main-number-btn-4',
  EurojackpotChooseMainNumber5Btn: '#ejp-main-number-btn-5',
  EurojackpotChooseMainNumber6Btn: '#ejp-main-number-btn-6',
  EurojackpotChooseMainNumber7Btn: '#ejp-main-number-btn-7',
  EurojackpotChooseMainNumber8Btn: '#ejp-main-number-btn-8',
  EurojackpotChooseMainNumber9Btn: '#ejp-main-number-btn-9',
  EurojackpotChooseMainNumber10Btn: '#ejp-main-number-btn-10',
  EurojackpotChooseMainNumber11Btn: '#ejp-main-number-btn-11',
  EurojackpotChooseMainNumber12Btn: '#ejp-main-number-btn-12',
  EurojackpotChooseMainNumber13Btn: '#ejp-main-number-btn-13',
  EurojackpotChooseMainNumber14Btn: '#ejp-main-number-btn-14',
  EurojackpotChooseMainNumber15Btn: '#ejp-main-number-btn-15',
  EurojackpotChooseMainNumber16Btn: '#ejp-main-number-btn-16',
  EurojackpotChooseMainNumber17Btn: '#ejp-main-number-btn-17',
  EurojackpotChooseMainNumber18Btn: '#ejp-main-number-btn-18',
  EurojackpotChooseMainNumber19Btn: '#ejp-main-number-btn-19',
  EurojackpotChooseMainNumber20Btn: '#ejp-main-number-btn-20',
  EurojackpotChooseMainNumber21Btn: '#ejp-main-number-btn-21',
  EurojackpotChooseMainNumber22Btn: '#ejp-main-number-btn-22',
  EurojackpotChooseMainNumber23Btn: '#ejp-main-number-btn-23',
  EurojackpotChooseMainNumber24Btn: '#ejp-main-number-btn-24',
  EurojackpotChooseMainNumber25Btn: '#ejp-main-number-btn-25',
  EurojackpotChooseMainNumber26Btn: '#ejp-main-number-btn-26',
  EurojackpotChooseMainNumber27Btn: '#ejp-main-number-btn-27',
  EurojackpotChooseMainNumber28Btn: '#ejp-main-number-btn-28',
  EurojackpotChooseMainNumber29Btn: '#ejp-main-number-btn-29',
  EurojackpotChooseMainNumber30Btn: '#ejp-main-number-btn-30',
  EurojackpotChooseMainNumber31Btn: '#ejp-main-number-btn-31',
  EurojackpotChooseMainNumber32Btn: '#ejp-main-number-btn-32',
  EurojackpotChooseMainNumber33Btn: '#ejp-main-number-btn-33',
  EurojackpotChooseMainNumber34Btn: '#ejp-main-number-btn-34',
  EurojackpotChooseMainNumber35Btn: '#ejp-main-number-btn-35',
  EurojackpotChooseMainNumber36Btn: '#ejp-main-number-btn-36',
  EurojackpotChooseMainNumber37Btn: '#ejp-main-number-btn-37',
  EurojackpotChooseMainNumber38Btn: '#ejp-main-number-btn-38',
  EurojackpotChooseMainNumber39Btn: '#ejp-main-number-btn-39',
  EurojackpotChooseMainNumber40Btn: '#ejp-main-number-btn-40',
  EurojackpotChooseMainNumber41Btn: '#ejp-main-number-btn-41',
  EurojackpotChooseMainNumber42Btn: '#ejp-main-number-btn-42',
  EurojackpotChooseMainNumber43Btn: '#ejp-main-number-btn-43',
  EurojackpotChooseMainNumber44Btn: '#ejp-main-number-btn-44',
  EurojackpotChooseMainNumber45Btn: '#ejp-main-number-btn-45',
  EurojackpotChooseMainNumber46Btn: '#ejp-main-number-btn-46',
  EurojackpotChooseMainNumber47Btn: '#ejp-main-number-btn-47',
  EurojackpotChooseMainNumber48Btn: '#ejp-main-number-btn-48',
  EurojackpotChooseMainNumber49Btn: '#ejp-main-number-btn-49',
  EurojackpotChooseMainNumber50Btn: '#ejp-main-number-btn-50',

  // Euro numbers 1-12
  EurojackpotChooseEuroNumbersLbl:
    '#eurojackpot > div > div.play-area-layout__play-area > div > div > div.eurojackpot-play-area__main > div:nth-child(2) > div.number-selection-layout__header',
  EurojackpotChooseEuroNumbers:
    '#eurojackpot > div > div.play-area-layout__play-area > div > div > div.eurojackpot-play-area__main > div:nth-child(2) > div.number-selection-layout__number-wrapper',
  EurojackpotChooseEuroNumber1Btn: '#ejp-euro-number-btn-1',
  EurojackpotChooseEuroNumber2Btn: '#ejp-euro-number-btn-2',
  EurojackpotChooseEuroNumber3Btn: '#ejp-euro-number-btn-3',
  EurojackpotChooseEuroNumber4Btn: '#ejp-euro-number-btn-4',
  EurojackpotChooseEuroNumber5Btn: '#ejp-euro-number-btn-5',
  EurojackpotChooseEuroNumber6Btn: '#ejp-euro-number-btn-6',
  EurojackpotChooseEuroNumber7Btn: '#ejp-euro-number-btn-7',
  EurojackpotChooseEuroNumber8Btn: '#ejp-euro-number-btn-8',
  EurojackpotChooseEuroNumber9Btn: '#ejp-euro-number-btn-9',
  EurojackpotChooseEuroNumber10Btn: '#ejp-euro-number-btn-10',
  EurojackpotChooseEuroNumber11Btn: '#ejp-euro-number-btn-11',
  EurojackpotChooseEuroNumber12Btn: '#ejp-euro-number-btn-12',

  // Statistics
  EurojackpotStatisticsLbl: '.eurojackpot-play-area__statistics-title',
  EurojackpotStatisticsSwitchLbl: '.tristate-switch',
  EurojackpotStatisticsSwitchOccurance:
    '#eurojackpot > div > div.play-area-layout__play-area > div > div > div.eurojackpot-play-area__footer > div.eurojackpot-play-area__statistics > div.tristate-switch > div:nth-child(1)',
  EurojackpotStatisticsSwitchMiddle:
    '#eurojackpot > div > div.play-area-layout__play-area > div > div > div.eurojackpot-play-area__footer > div.eurojackpot-play-area__statistics > div.tristate-switch > div:nth-child(2)',
  EurojackpotStatisticsSwitchDelays:
    '#eurojackpot > div > div.play-area-layout__play-area > div > div > div.eurojackpot-play-area__footer > div.eurojackpot-play-area__statistics > div.tristate-switch > div:nth-child(3)',

  // Main numbers Statistics 1-50
  EurojackpotChooseMainNumberStatistics1Btn: '#ejp-main-number-btn-1 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics2Btn: '#ejp-main-number-btn-2 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics3Btn: '#ejp-main-number-btn-3 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics4Btn: '#ejp-main-number-btn-4 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics5Btn: '#ejp-main-number-btn-5 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics6Btn: '#ejp-main-number-btn-6 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics7Btn: '#ejp-main-number-btn-7 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics8Btn: '#ejp-main-number-btn-8 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics9Btn: '#ejp-main-number-btn-9 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics10Btn: '#ejp-main-number-btn-10 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics11Btn: '#ejp-main-number-btn-11 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics12Btn: '#ejp-main-number-btn-12 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics13Btn: '#ejp-main-number-btn-13 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics14Btn: '#ejp-main-number-btn-14 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics15Btn: '#ejp-main-number-btn-15 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics16Btn: '#ejp-main-number-btn-16 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics17Btn: '#ejp-main-number-btn-17 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics18Btn: '#ejp-main-number-btn-18 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics19Btn: '#ejp-main-number-btn-19 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics20Btn: '#ejp-main-number-btn-20 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics21Btn: '#ejp-main-number-btn-21 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics22Btn: '#ejp-main-number-btn-22 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics23Btn: '#ejp-main-number-btn-23 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics24Btn: '#ejp-main-number-btn-24 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics25Btn: '#ejp-main-number-btn-25 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics26Btn: '#ejp-main-number-btn-26 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics27Btn: '#ejp-main-number-btn-27 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics28Btn: '#ejp-main-number-btn-28 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics29Btn: '#ejp-main-number-btn-29 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics30Btn: '#ejp-main-number-btn-30 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics31Btn: '#ejp-main-number-btn-31 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics32Btn: '#ejp-main-number-btn-32 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics33Btn: '#ejp-main-number-btn-33 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics34Btn: '#ejp-main-number-btn-34 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics35Btn: '#ejp-main-number-btn-35 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics36Btn: '#ejp-main-number-btn-36 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics37Btn: '#ejp-main-number-btn-37 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics38Btn: '#ejp-main-number-btn-38 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics39Btn: '#ejp-main-number-btn-39 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics40Btn: '#ejp-main-number-btn-40 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics41Btn: '#ejp-main-number-btn-41 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics42Btn: '#ejp-main-number-btn-42 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics43Btn: '#ejp-main-number-btn-43 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics44Btn: '#ejp-main-number-btn-44 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics45Btn: '#ejp-main-number-btn-45 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics46Btn: '#ejp-main-number-btn-46 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics47Btn: '#ejp-main-number-btn-47 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics48Btn: '#ejp-main-number-btn-48 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics49Btn: '#ejp-main-number-btn-49 > span.eurojackpot-number-button__info',
  EurojackpotChooseMainNumberStatistics50Btn: '#ejp-main-number-btn-50 > span.eurojackpot-number-button__info',

  // Euro numbers Statistics 1-12
  EurojackpotChooseEuroNumberStatistics1Btn: '#ejp-euro-number-btn-1 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics2Btn: '#ejp-euro-number-btn-2 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics3Btn: '#ejp-euro-number-btn-3 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics4Btn: '#ejp-euro-number-btn-4 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics5Btn: '#ejp-euro-number-btn-5 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics6Btn: '#ejp-euro-number-btn-6 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics7Btn: '#ejp-euro-number-btn-7 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics8Btn: '#ejp-euro-number-btn-8 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics9Btn: '#ejp-euro-number-btn-9 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics10Btn: '#ejp-euro-number-btn-10 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics11Btn: '#ejp-euro-number-btn-11 > span.eurojackpot-number-button__info',
  EurojackpotChooseEuroNumberStatistics12Btn: '#ejp-euro-number-btn-12 > span.eurojackpot-number-button__info',

  // Side screen
  EurojackpotBetslipPreview: '.sidescreen-layout__content',
  EurojackpotBetslipAreaA: '#ejp-selections-0',
  EurojackpotBetslipAreaB: '#ejp-selections-1',
  EurojackpotBetslipAreaC: '#ejp-selections-2',
  EurojackpotBetslipAreaD: '#ejp-selections-3',
  EurojackpotBetslipAreaE: '#ejp-selections-4',
  EurojackpotBetslipAreaF: '#ejp-selections-5',
  EurojackpotBetslipAreaACost: '#ejp-selections-0 > div > div.eurojackpot-selections__header > div > span',
  EurojackpotBetslipAreaBCost: '#ejp-selections-1 > div > div.eurojackpot-selections__header > div > span',
  EurojackpotBetslipAreaCCost: '#ejp-selections-2 > div > div.eurojackpot-selections__header > div > span',
  EurojackpotBetslipAreaDCost: '#ejp-selections-3 > div > div.eurojackpot-selections__header > div > span',
  EurojackpotBetslipAreaECost: '#ejp-selections-4 > div > div.eurojackpot-selections__header > div > span',
  EurojackpotBetslipAreaFCost: '#ejp-selections-5 > div > div.eurojackpot-selections__header > div > span',
  EurojackpotBetslipSystemA:
    '#ejp-selections-0 > div > div.eurojackpot-selections__header > div.eurojackpot-selections__header-system',
  EurojackpotBetslipSystemB:
    '#ejp-selections-1 > div > div.eurojackpot-selections__header > div.eurojackpot-selections__header-system',
  EurojackpotBetslipSystemC:
    '#ejp-selections-2 > div > div.eurojackpot-selections__header > div.eurojackpot-selections__header-system',
  EurojackpotBetslipSystemD:
    '#ejp-selections-3 > div > div.eurojackpot-selections__header > div.eurojackpot-selections__header-system',
  EurojackpotBetslipSystemE:
    '#ejp-selections-4 > div > div.eurojackpot-selections__header > div.eurojackpot-selections__header-system',
  EurojackpotBetslipSystemF:
    '#ejp-selections-5 > div > div.eurojackpot-selections__header > div.eurojackpot-selections__header-system',
  EurojackpotBetslipAreaAClear: '#ejp-selections-delete-0',
  EurojackpotBetslipAreaBClear: '#ejp-selections-delete-1',
  EurojackpotBetslipAreaCClear: '#ejp-selections-delete-2',
  EurojackpotBetslipAreaDClear: '#ejp-selections-delete-3',
  EurojackpotBetslipAreaEClear: '#ejp-selections-delete-4',
  EurojackpotBetslipAreaFClear: '#ejp-selections-delete-5',

  EurojackpotBetslipAddBet: '#eurojackpot_preview_add_new_game',

  // Side screen Consecutive Draws & Submit
  EurojackpotBetConsDrawsArea: '.consecutive-draws',
  EurojackpotBetConsDrawsLbl: '#ssbt_consecutive_draws_header_text',
  EurojackpotBetConsDrawsPlus: '#ssbt_increase_consecutive_draws_button',
  EurojackpotBetConsDrawsMinus: '#ssbt_decrease_consecutive_draws_button',
  EurojackpotBetConsDrawsInput: '#consecutive-draws-input',

  EurojackpotBetslipSubmitBtn: '.submit-button__printBetslip',
  EurojackpotBetslipSubmitLbl: '#ssbt_place_bet_text',
  EurojackpotBetslipCostLbl: '.submit-button__printBetslip-cost',
  EurojackpotBetslipCost: '#ssbt_betslip_value',
  EurojackpotBetslipPlaceBetInfo: '.submit-button__info',

  EurojackpotBetConsDrawsCalc1: '#consDraws_keypad_1',
  EurojackpotBetConsDrawsCalc2: '#consDraws_keypad_2',
  EurojackpotBetConsDrawsCalc3: '#consDraws_keypad_3',
  EurojackpotBetConsDrawsCalc4: '#consDraws_keypad_4',
  EurojackpotBetConsDrawsCalc5: '#consDraws_keypad_5',
  EurojackpotBetConsDrawsCalc6: '#consDraws_keypad_6',
  EurojackpotBetConsDrawsCalc7: '#consDraws_keypad_7',
  EurojackpotBetConsDrawsCalc8: '#consDraws_keypad_8',
  EurojackpotBetConsDrawsCalc9: '#consDraws_keypad_9',
  EurojackpotBetConsDrawsCalc0: '#consDraws_keypad_0',
  EurojackpotBetConsDrawsCalcCE: '#consDraws_ce_button',
  EurojackpotBetConsDrawsCalcOK: '#consDraws_ok_button',
  EurojackpotBetConsDrawsCalcMsg: '#sidescreen_consDraws_toastrMsg',

  // clear msg
  EurojackpotModalAMsgLbl: '#info-modal-title',
  EurojackpotModalAMsg: '#info-modal-message',
  EurojackpotModalAYesBtn: '#yes-option',
  EurojackpotModalANoBtn: '#no-option',
};
