const moduleTypes = {
  PLAYER_SESSION_MODULE: 'PLAYER_SESSION_MODULE',
  CONFIGURATION_STORE_MODULE: 'CONFIGURATION_STORE_MODULE',
  SESSION_STORE_MODULE: 'SESSION_STORE_MODULE',
  SERVICE_CHECK_STORE_MODULE: 'SERVICE_CHECK_STORE_MODULE',
  KINO_GAME_STORE_MODULE: 'KINO_GAME_STORE_MODULE',
  EUROJACKPOT_GAME_STORE_MODULE: 'EUROJACKPOT_GAME_STORE_MODULE',
  POWERSPIN_GAME_STORE_MODULE: 'POWERSPIN_GAME_STORE_MODULE',
  FIREBLAZE_GAME_STORE_MODULE: 'FIREBLAZE_GAME_STORE_MODULE',
  TZOKER_GAME_STORE_MODULE: 'TZOKER_GAME_STORE_MODULE',
};

export default moduleTypes;
