export default {
  DRAW_INFORMATION: {
    POLLING_INTERVAL_MILLIS: 2000,
    FIRST_POLLING_INTERVAL_MILLIS: 1200,
    POLLING_INTERVAL_ON_ERROR_MILLIS: 60000,
  },
  SCREEN_MODE: {
    PORTRAIT: 'portrait',
    LANDSCAPE: 'landscape',
  },
  LIVE_DRAW: {
    DEFAULT_THEME: 'classic',
    DEFAULT_THEME_TYPE: 'simple',
  },
  SIMPLE_PARTICIPATION_THRESHOLD: 3,
  PRINT_TYPE: {
    QR_CODE: 1,
    BETSLIP: 2,
    VOUCHER: 3,
    POWERSPIN_BETSLIP: 4,
    EUROJACKPOT_BETSLIP: 5,
    FIREBLAZE_BETSLIP: 6,
    INSTANT_WIN_VOUCHER: 7,
    TZOKER_BETSLIP: 8,
  },
  SERIAL_NUMBER_LENGTH: {
    L5: 35,
    L5_FULL: 36,
    L10: 32,
    L10_LOTTO: 29,
    L10_FULL: 57,
    VOUCHER_PROMO_CODE_LENGTH: 29,
  },
  ISECURE_LENGTH: 10,
  QRCODE_OPTIONS: {
    version: 3,
    errorCorrectionLevel: 'H',
    type: 'image/jpeg',
    rendererOpts: {
      quality: 1,
    },
    scale: 4,
  },
  BOOK_OF_GAMES_QRCODE_OPTIONS: {
    errorCorrectionLevel: 'H',
    type: 'image/jpeg',
    rendererOpts: {
      quality: 1,
    },
    width: 188,
    color: {
      light: '#D9D9D9',
    },
  },
  ILOT_GAMETYPES: {
    BET_WITHOUT_KINO_BONUS: 1,
    BET_WITH_KINO_BONUS: 2,
    ODD: 3,
    EVEN: 4,
    DRAW: 5,
    COLUMNS: 6,
    BET_WITH_CLOSE_2_WIN: 24,
    BET_WITH_CLOSE_2_WIN_AND_KINO_BONUS: 25,
  },
  GAME_IDS: {
    KINO: 1100,
    POWERSPIN: 1110,
    EUROJACKPOT: 5149,
    FIREBLAZE: 1200,
    TZOKER: 5104,
  },
  RECEIPT_L10_EXTRA_HEIGHT: 180,
  RECEIPT_VERTICAL_SPACE: 80,
  RECEIPT_WIDTH: 512,
  RECEIPT_DEFAULT_HEIGHT: 800,
  RECEIPT_ROW_HEIGHT: 34,
  RECEIPT_IW_HEIGHT: 105,
  RECEIPT_LOGO_HEIGHT: 84,
  BETSLIP_TOTAL_COST_ROW_HEIGHT: 42,
  PDF417_BARCODE_HEIGHT: 70,
  CODE_128_BARCODE_HEIGHT: 110,
  COMPANY_INFO_HEIGHT: 80,
  RECEIPT_FILL_COLOR: 'white',
  DEFAULT_LOCALE: 'el',
  NUMBER_FORMATTER: new Intl.NumberFormat('el-EL', {
    minimumFractionDigits: 2,
  }),
  SIMPLE_NUMBER_FORMATTER: new Intl.NumberFormat('el-EL'),
  findWinnings: {
    tiers: [
      {
        type: 'low',
        highLimitExlusive: 1000,
      },
      {
        type: 'mid',
        lowLimitInclusive: 1000,
        highLimitExlusive: 2000,
      },
      {
        type: 'high',
        lowLimitInclusive: 2000,
        highLimitExlusive: 100000,
      },
      {
        type: 'special',
        lowLimitInclusive: 100000,
      },
    ],
  },
  MIN_CONSECUTIVE_DRAWS_VALUE: 1,
  KINO_MAX_CONSECUTIVE_DRAWS_VALUE: 800,
  POWERSPIN_MAX_CONSECUTIVE_DRAWS_VALUE: 400,
  FIREBLAZE_MAX_CONSECUTIVE_DRAWS_VALUE: 400,
  TZOKER_MAX_CONSECUTIVE_DRAWS_VALUE: 12,
  MIN_MULTIPLIER_VALUE: 1,
  MAX_MULTIPLIER_VALUE: 99,
  ssbtUserType: 104,
  SSBT_GET_GENERIC_TOKEN: {
    AUTHORIZATION: {
      USERNAME: 'ssbts',
    },
    GRANT_TYPE: 'client_credentials',
  },
  SSBT_GET_TOKEN: {
    AUTHORIZATION: {
      USERNAME: 'ssbts',
    },
    GRANT_TYPE_TERMINAL: 'http://betware.com/oidc/grant-type/ssbt.terminal',
    SCOPE: 'http://betware.com/oidc/scopes/session',
  },
  SSBT_GET_VOUCHER_INFO: {
    CHANNELID: '2',
  },
  CSRF: {
    'x-csrftoken': 'X',
    Cookie: 'csrftoken=X',
    'Cache-Control': 'no-cache',
  },
  CONTENT_TYPE: {
    JSON: 'application/json',
    URLENCODED: 'application/x-www-form-urlencoded',
  },
  GET_VOUCHER_INFO: {
    ERROR: {
      USED_VOUCHER: {
        TYPE: {
          FROM_APOLLO: 'normal',
          FROM_SSBT: 'cashout',
        },
        STATUS: {
          REDEEMED: 'redeemed',
          CANCELED: 'canceled',
          CASHEDOUT: 'cashedout',
        },
      },
    },
  },
  GET_TOKEN: {
    ERROR: {
      USED_VOUCHER: 'USED_VOUCHER',
      CASHED_OUT_VOUCHER: 'CASHED_OUT_VOUCHER',
    },
  },
  DEPOSIT_VOUCHER: {
    ERROR: {
      LIMIT_EXCEEDED: 'SSBT_LIMIT_EXCEEDED',
      NOT_ALLOWED_ACTION_FOR_RETAILER_ERROR: 'NOT_ALLOWED_ACTION_FOR_RETAILER_ERROR',
    },
  },
  PLACE_BET: {
    ERROR: {
      BALANCE_INSUFFICIENT: 'BALANCE_INSUFFICIENT',
      MAX_CAP_ERROR_CODE: '870069',
      MAX_CONSECUTIVE_DRAWS_ERROR: '870019',
      UNAVAILABLE_DRAW_ERROR: 'UNAVAILABLE_DRAW_ERROR',
    },
  },
  BARCODE_DATA: {
    LOTTERY_SERIAL_NUMBER_PREFIX: '0',
    VOUCHER_CODE_LENGTH: 28,
    LOTTERY_GAMES_CODE_LENGTH: 36,
    HELLENIC_LOTTERY_CODE_LENGTH: 30,
    SCRATCH_CODE_LENGTH: 28,
  },
  POWERSPIN_PLAY_MODE: {
    WHEELS: 'WHEELS',
    MARKETS: 'MARKETS',
  },
  BASIC_BETTING_AMOUNT: 0.5,
  MULTIPLIERS_SET: [1, 2, 3, 4, 5, 6, 8, 10, 20, 40],
  ODD_EVEN_COLUMNS_AMOUNTS: [1, 2, 3, 5, 10, 15, 20, 30, 50, 100],
  ODD_EVEN_VALUES: ['odd', 'even', 'draw'],
  KINO_GAMES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  KINO_CLOSE_2_WIN_GAMES: [2, 3, 4, 5, 6, 7, 8, 9],
  PAY_TABLES: {
    KINO: [
      [0],
      [0, 2.5],
      [0, 1, 5],
      [0, 0, 2.5, 25],
      [0, 0, 1, 4, 100],
      [0, 0, 0, 2, 20, 450],
      [0, 0, 0, 1, 7, 50, 1600],
      [0, 0, 0, 1, 3, 20, 100, 5000],
      [0, 0, 0, 0, 2, 10, 50, 1000, 15000],
      [0, 0, 0, 0, 1, 5, 25, 200, 4000, 40000],
      [2, 0, 0, 0, 0, 2, 20, 80, 500, 10000, 100000],
      [2, 0, 0, 0, 0, 1, 10, 50, 250, 1500, 15000, 500000],
      [4, 0, 0, 0, 0, 0, 5, 25, 150, 1000, 2500, 25000, 1000000],
    ],
    KINOBONUS: [
      [0],
      [0, 52.5],
      [0, 16, 70],
      [0, 8, 18, 175],
      [0, 5, 8, 24, 600],
      [0, 3, 5, 17, 90, 1350],
      [0, 2, 3, 9, 27, 300, 4100],
      [0, 2, 3, 8, 13, 80, 400, 15000],
      [0, 2, 3, 4, 7, 30, 200, 3000, 40000],
      [0, 2, 3, 4, 6, 15, 70, 500, 10000, 100000],
      [0, 2, 2.5, 3, 4, 7, 60, 180, 1500, 25000, 250000],
      [0, 2, 2.5, 3, 4, 6, 25, 105, 550, 3500, 31000, 1200000],
      [0, 2, 2.5, 3, 3.5, 4, 10, 50, 350, 2200, 5500, 75000, 2000000],
    ],
    C2W: [0, 0, 2, 5, 16, 60, 230, 900, 4200, 20000, 0, 0, 0],
  },
  MAX_KINO_WINNING_AMOUNT: 1000000,
  MAX_KINO_BONUS_WINNING_AMOUNT: 2000000,
  FIND_WINNINGS: {
    TICKET_STATUS: {
      WON: 'WON',
      BLOCKED: 'BLOCKED',
      CANCELLED: 'CANCELLED',
      INVALID: 'INVALID',
      PENDING_PRIZE_BREAKDOWN: 'PENDING_PRIZE_BREAKDOWN',
      CLAIMED: 'CLAIMED',
      COPY: 'COPY',
      COPY_CLAIMED: 'COPY_CLAIMED',
    },
    TIER: {
      SPECIAL_LIST: ['high', 'special'],
      REGULAR_LIST: ['low', 'mid'],
    },
    MESSAGES: {
      HIGH_WIN: 'findWinnings.highWinnings',
      SPECIAL_WIN: 'findWinnings.specialWinnings',
      CONTACT_AGENT: 'findWinnings.contactAgent',
    },
    AUTO_CLOSE_TIMEOUT: 10000,
  },
  BAR_CODE_COLOR: 'white',
  GENERAL_GAME_TYPES: {
    KINO: 'KINO',
    POWERSPIN: 'POWERSPIN',
    FIREBLAZE: 'FIREBLAZE',
    EUROJACKPOT: 'EUROJACKPOT',
    LOTTO: 'LOTTO',
    TZOKER: 'TZOKER',
    JOKER: 'JOKER',
  },
  SSBT_GAME_TYPES: {
    KINO: 'KINO',
    POWERSPIN: 'POWERSPIN',
    FIREBLAZE: 'FIREBLAZE',
    EUROJACKPOT: 'EUROJACKPOT',
    TZOKER: 'TZOKER',
  },
  SSBT_GAME_NAMES: {
    KINO: 'KINO',
    POWERSPIN: 'POWERSPIN',
    FIREBLAZE: 'POWERSPIN ON FIRE',
    EUROJACKPOT: 'EUROJACKPOT',
    TZOKER: 'ΤΖΟΚΕΡ',
  },
  THEMES: {
    KINO: 'kino',
    POWERSPIN: 'powerspin',
    TZOKER: 'tzoker',
  },
  GAMETYPES_MAPPER: {
    POWERSPIN: 'powerspin',
    KINO: 'kino',
    EUROJACKPOT: 'eurojackpot',
    FIREBLAZE: 'powerspin',
    TZOKER: 'tzoker',
  },
  ROUTE_TO_ASSET_MAP: {
    kino: 'kino',
    kinofaq: 'kino',
    'kinoFaq-details': 'kino',
    'kino-quickplay': 'kino',
    quickbets: 'kino',
    powerspin: 'powerspin',
    powerspinfaq: 'powerspin',
    'powerspinFaq-details': 'powerspin',
    fireblaze: 'powerspin',
    eurojackpot: 'eurojackpot',
    powerspin_quickplay: 'powerspin',
    powerspin_quickbets: 'powerspin',
    'kino-videos': 'kino',
    'powerspin-videos': 'powerspin',
    tzoker: 'tzoker',
  },
  ROUTE_TO_CSS_MAP: {
    kino: 'KINO',
    kinofaq: 'KINO',
    'kinoFaq-details': 'KINO',
    'kino-quickplay': 'KINO',
    quickbets: 'KINO',
    powerspin: 'POWERSPIN',
    powerspinfaq: 'POWERSPIN',
    'powerspinFaq-details': 'POWERSPIN',
    fireblaze: 'FIREBLAZE',
    eurojackpot: 'EUROJACKPOT',
    powerspin_quickplay: 'POWERSPIN',
    powerspin_quickbets: 'POWERSPIN',
    'kino-videos': 'KINO',
    'powerspin-videos': 'POWERSPIN',
    tzoker: 'TZOKER',
  },
  IMAGE_NAMES: {
    KINO_BANNER_IMAGE: 'KINO_BANNER_IMAGE',
    POWERSPIN_BANNER_IMAGE: 'POWERSPIN_BANNER_IMAGE',
  },
  VIDEO_NAMES: {
    LOBBY: 'LOBBY',
    FAQ_LOBBY: 'FAQ_LOBBY',
    FAQ_KINO_ANSWERS: 'FAQ_KINO_ANSWERS',
    FAQ_POWERSPIN_ANSWERS: 'FAQ_POWERSPIN_ANSWERS',
    FAQ_OTHER_ANSWERS: 'FAQ_OTHER_ANSWERS',
    FAQ_KINO_QUESTIONS: 'FAQ_KINO_QUESTIONS',
    FAQ_POWERSPIN_QUESTIONS: 'FAQ_POWERSPIN_QUESTIONS',
    FAQ_OTHER_QUESTIONS: 'FAQ_OTHER_QUESTIONS',
    DIGITAL_ASSISTANT: 'DIGITAL_ASSISTANT',
    HOW_TO_LOBBY: 'HOW_TO_LOBBY',
    HOW_TO_KINO_1: 'HOW_TO_KINO_1',
    HOW_TO_KINO_2: 'HOW_TO_KINO_2',
    HOW_TO_POWERSPIN_1: 'HOW_TO_POWERSPIN_1',
    HOW_TO_POWERSPIN_2: 'HOW_TO_POWERSPIN_2',
    SCREENSAVER: 'SCREENSAVER',
  },
  ROUTE_NAMES: {
    LOBBY: 'lobby',
    KINO: 'kino',
    KINO_QUICKPLAY: 'kino-quickplay',
    POWERSPIN_QUICKPLAY: 'powerspin_quickplay',
    QUICKBETS: 'quickbets',
    POWERSPIN_QUICKBETS: 'powerspin_quickbets',
    POWERSPIN: 'powerspin',
    FIREBLAZE: 'fireblaze',
    EUROJACKPOT: 'eurojackpot',
    TZOKER: 'tzoker',
    BOOK_OF_GAMES: 'book-of-games',
    DIGITAL_ASSISTANT: 'digitalAssistant',
    SCREENSAVER: 'screensaver',
    HELP_SECTION: 'helpsection',
    HOWTO_LOBBY: 'howto-lobby',
    KINO_VIDEOS: 'kino-videos',
    POWERSPIN_VIDEOS: 'powerspin-videos',
    KINO_FAQ: 'kinofaq',
    POWERSPIN_FAQ: 'powerspinfaq',
    HELP_FAQ: 'helpfaq',
    HELP_FAQ_DETAILS: 'helpFaq-details',
    POWERSPIN_FAQ_DETAILS: 'powerspinFaq-details',
    HELP: 'help',
    KINO_FAQ_DETAILS: 'kinoFaq-details',
    MAIN_FAQ: 'mainfaq',
  },
  BOOK_OF_GAMES_URLS: {
    GENERAL_GAMES: 'https://media.opap.gr/odhgoi_paigniwn.pdf',
    OPAP_PLAY: 'https://media.opap.gr/Swf/BOG_Full.pdf',
  },
  ODD_EVEN_PAY: 2,
  ODD_EVEN_PAY_DRAW: 4,
  COLUMNS_PAY: 8,
  COLUMNS_IMAGES: {
    FILLED: 'stili-filled.png',
    EMPTY: 'stili-empty.png',
  },
  ODD_EVEN_DRAW_IMAGES: {
    ODD: {
      LOGO: 'mona-logo.png',
      GRAPHIC: 'zygaria-mona.png',
    },
    EVEN: {
      LOGO: 'zyga-logo.png',
      GRAPHIC: 'zygaria-zyga.png',
    },
    DRAW: {
      LOGO: 'isopalia-logo.png',
      GRAPHIC: 'zygaria-isopalia.png',
    },
  },
  GENERAL_AUTO_CLOSE_TIMEOUT: 5000,
  ALLOWED_ORIGINS: ['https://ds.opap.gr', 'https://dsuat.opap.gr'],
  PROMOTIONS_VOUCHER_MESSAGES: {
    SECOND_CHANCE_NO_RAFFLE: 'promotions.secondChanceNoRaffle',
    SECOND_CHANCE_CANCELLED: 'promotions.secondChanceCancelled',
    SECOND_CHANCE_EXPIRED: 'promotions.secondChanceExpired',
    GIFTS_EXPIRED: 'promotions.giftsExpired',
    SECOND_CHANCE_RAFFLE_NO_WIN: 'promotions.secondChanceRaffleNoWin',
    SECOND_CHANCE_RAFFLE_WIN: 'promotions.secondChanceRaffleWin',
    SECOND_CHANCE_RAFFLE_WIN_ALLWYN: 'promotions.secondChanceRaffleWinAllwyn',
    SECOND_CHANCE_REDEEMED: 'promotions.secondChanceRedeemed',
    GIFTS_REDEEMED: 'promotions.giftsRedeemed',
    SECOND_CHANCE_INVALID: 'promotions.secondChanceInvalid',
    INSTANT_WIN_SUCCESS: 'promotions.instantWinSuccess',
    INSTANT_WIN_CANCELLED: 'promotions.instantWinCancelled',
    INSTANT_WIN_EXPIRED: 'promotions.instantWinExpired',
    INSTANT_WIN_REDEEMED: 'promotions.instantWinRedeemed',
  },
  PROMOTIONS_VOUCHER_STATUS: {
    FREE: 'Free',
    CANCELLED: 'Cancelled',
    REDEEMED: 'Redeemed',
  },
  PROMOTIONS_VOUCHER_OUTCOME_TYPE: {
    SECOND_CHANCE: 'SecondChanceDrawTickets',
    GIFTS: 'Gifts',
    NON_WIN: 'NonWin',
  },
  PROMOTIONS_INSTANT_WIN_OUTCOME: 'RealMoney',
  PROMOTIONS_MODAL_THEME: 'PROMOTIONS',
  SCREEN_WIDTH: 1920,
  BOX_NUMBER: 5,
  DRAW_RANGE: {
    EUROJACKPOT: 12,
    FIREBLAZE: 250,
    TZOKER: 12,
  },
  QUICKBETS: {
    DEFAULT_KINO_NUMBERS: 6,
  },
  DRAW_DAYS: 7,
  BRAND_NAMES: {
    ALLWYN: 'ALLWYN',
    OPAP: 'OPAP',
  },
  LOBBY_HEADER_THEMES: {
    LOBBY: 'lobby',
    ALLWYN: 'allwyn',
    KINO: 'kino',
    POWERSPIN: 'powerspin',
    FIREBLAZE: 'fireblaze',
    EUROJACKPOT: 'eurojackpot',
    EUROJACKPOT_EXTRA: 'eurojackpotExtra',
    TZOKER: 'tzoker',
  },
  PRINT_LOGO_ORIENTATION: {
    VERTICAL: 'VERTICAL',
    HORIZONTAL: 'HORIZONTAL',
  },
  FALLBACK_VIDEO: 'https://media.opap.gr/TzokerAccVids/opaponline_Register.mp4',
  HORIZONTAL: 'horizontal',
  GAME_LOGOS: {
    TZOKER: 'tzoker',
  },
  SSBT_ORIENTATION: {
    VERTICAL: 'VERTICAL',
    HORIZONTAL: 'HORIZONTAL',
  },
  TZOKER: {
    MIN_MAIN: 5,
    MAX_MAIN: 45,
    MIN_TZOKER: 1,
    MAX_TZOKER: 20,
    MAX_BOARDS: 12,
    BASE_COST: 1,
  },
};
