import moduleTypes from '../types';

const actionTypes = {
  RESET_BALANCE: 'RESET_BALANCE',
  RESET_ACCESS_TOKEN: 'RESET_ACCESS_TOKEN',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_BALANCE: 'SET_BALANCE',
  SET_SSBT_ID: 'SET_SSBT_ID',
  SET_GAME_TYPE: 'SET_GAME_TYPE',
  SAVE_KINO_BETSLIP: 'SAVE_KINO_BETSLIP',
  CLEAR_SAVED_KINO_BETSLIP: 'CLEAR_SAVED_KINO_BETSLIP',
  SET_BETSLIP_CONSECUTIVE_DRAWS: 'SET_BETSLIP_CONSECUTIVE_DRAWS',
  TOGGLE_BALANCE_VISIBILITY: 'TOGGLE_BALANCE_VISIBILITY',
  SET_BALANCE_VISIBILITY: 'SET_BALANCE_VISIBILITY',
};

const mutationTypes = {
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_BALANCE: 'SET_BALANCE',
  SET_SSBT_ID: 'SET_SSBT_ID',
  SET_GAME_TYPE: 'SET_GAME_TYPE',
  SAVE_KINO_BETSLIP: 'SAVE_KINO_BETSLIP',
  CLEAR_SAVED_KINO_BETSLIP: 'CLEAR_SAVED_KINO_BETSLIP',
  SET_BALANCE_VISIBILITY: 'SET_BALANCE_VISIBILITY',
};

const getterTypes = {
  GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
  GET_BALANCE: 'GET_BALANCE',
  GET_IS_ZERO_BALANCE: 'GET_IS_ZERO_BALANCE',
  GET_SSBT_ID: 'GET_SSBT_ID',
  GET_ACTIVE_SESSION: 'GET_ACTIVE_SESSION',
  IS_KINO_GAME: 'IS_KINO_GAME',
  GET_GAME_TYPE: 'GET_GAME_TYPE',
  GET_ACTIVE_BETSLIP_COST: 'GET_ACTIVE_BETSLIP_COST',
  GET_ACTIVE_BETSLIP_CONSECUTIVE_DRAWS: 'GET_ACTIVE_BETSLIP_CONSECUTIVE_DRAWS',
  GET_BALANCE_VISIBILITY: 'GET_BALANCE_VISIBILITY',
};

const state = {
  GAME_TYPE: 'gameType',
};

const namespaceMapper = {
  GET_GAME_TYPE: `${moduleTypes.SESSION_STORE_MODULE}/${getterTypes.GET_GAME_TYPE}`,
  GET_BALANCE_VISIBILITY: `${moduleTypes.SESSION_STORE_MODULE}/${getterTypes.GET_BALANCE_VISIBILITY}`,
  TOGGLE_BALANCE_VISIBILITY: `${moduleTypes.SESSION_STORE_MODULE}/${getterTypes.TOGGLE_BALANCE_VISIBILITY}`,
};

const types = {
  mutations: { ...mutationTypes },
  actions: { ...actionTypes },
  getters: { ...getterTypes },
  namespaceMapper: { ...namespaceMapper },
  state,
};

export default types;
