import moduleTypes from '../types/types';

const MODULE_NAME = moduleTypes.POWERSPIN_GAME_STORE_MODULE;

const state = {
  BETSLIP_ARRAY: 'betslipArray',
  SELECTED_BETSLIP_INDEX: 'selectedBetslipIndex',
  QUICKPLAY_BETSLIP_DATA: 'quickplayBetslipData',
};

const mutations = {
  SET_BETSLIP_ARRAY: 'SET_BETSLIP_ARRAY',
  SET_SELECTED_BETSLIP_INDEX: 'SET_SELECTED_BETSLIP_INDEX',
  ADD_BETSLIP: 'ADD_BETSLIP',
  REMOVE_BETSLIP: 'REMOVE_BETSLIP',
  RESET_BETSLIP: 'RESET_BETSLIP',
  RESET_ALL_BETSLIPS: 'RESET_ALL_BETSLIPS',
  SET_MODE: 'SET_MODE',
  SET_COMBO_MODE: 'SET_COMBO_MODE',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
  ADD_WHEEL: 'ADD_WHEEL',
  REMOVE_WHEEL: 'REMOVE_WHEEL',
  SET_QUICKPLAY_BETSLIP_DATA: 'SET_QUICKPLAY_BETSLIP_DATA',
  TOGGLE_MULTIPLIERS: 'TOGGLE_MULTIPLIERS',
  TOGGLE_GAME_TYPE: 'TOGGLE_GAME_TYPE',
  SET_REQUESTED_NUMBER: 'SET_REQUESTED_NUMBER',
  SET_COLUMN_NUMBER: 'SET_COLUMN_NUMBER',
  QUICK_PICK: 'QUICK_PICK',
  SET_MARKETS_NUMBER_ON_ANY_WHEEL: 'SET_MARKETS_NUMBER_ON_ANY_WHEEL',
  TOGGLE_MARKET_GAME_TYPE: 'TOGGLE_MARKET_GAME_TYPE',
  TOGGLE_MARKET_MULTIPLIERS: 'TOGGLE_MARKET_MULTIPLIERS',
  RESET_CATEGORY: 'RESET_CATEGORY',
  RESET_WHEELS: 'RESET_WHEELS',
};

const actions = {
  SET_BETSLIP_ARRAY: 'SET_BETSLIP_ARRAY',
  SET_SELECTED_BETSLIP_INDEX: 'SET_SELECTED_BETSLIP_INDEX',
  ADD_BETSLIP: 'ADD_BETSLIP',
  REMOVE_BETSLIP: 'REMOVE_BETSLIP',
  RESET_BETSLIP: 'RESET_BETSLIP',
  RESET_ALL_BETSLIPS: 'RESET_ALL_BETSLIPS',
  SET_MODE: 'SET_MODE',
  SET_COMBO_MODE: 'SET_COMBO_MODE',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
  ADD_WHEEL: 'ADD_WHEEL',
  REMOVE_WHEEL: 'REMOVE_WHEEL',
  SET_QUICKPLAY_BETSLIP_DATA: 'SET_QUICKPLAY_BETSLIP_DATA',
  TOGGLE_MULTIPLIERS: 'TOGGLE_MULTIPLIERS',
  TOGGLE_GAME_TYPE: 'TOGGLE_GAME_TYPE',
  SET_REQUESTED_NUMBER: 'SET_REQUESTED_NUMBER',
  SET_COLUMN_NUMBER: 'SET_COLUMN_NUMBER',
  QUICK_PICK_CLICKED: 'QUICK_PICK_CLICKED',
  SET_MARKETS_NUMBER_ON_ANY_WHEEL: 'SET_MARKETS_NUMBER_ON_ANY_WHEEL',
  TOGGLE_MARKET_GAME_TYPE: 'TOGGLE_MARKET_GAME_TYPE',
  TOGGLE_MARKET_MULTIPLIERS: 'TOGGLE_MARKET_MULTIPLIERS',
  RESET_CATEGORY: 'RESET_CATEGORY',
  RESET_WHEELS: 'RESET_WHEELS',
};

const getters = {
  GET_BETSLIP_ARRAY: 'GET_BETSLIP_ARRAY',
  GET_SELECTED_BETSLIP_INDEX: 'GET_SELECTED_BETSLIP_INDEX',
  GET_SELECTED_BETSLIP: 'GET_SELECTED_BETSLIP',
  GET_CATEGORY_COST: 'GET_CATEGORY_COST',
  GET_WHEEL_COST: 'GET_WHEEL_COST',
  GET_WHEELS_COST: 'GET_WHEELS_COST',
  GET_MARKETS_COST: 'GET_MARKETS_COST',
  GET_BETSLIP_COST: 'GET_BETSLIP_COST',
  GET_TOTAL_COST: 'GET_TOTAL_COST',
  GET_IS_BETSLIP_VALID: 'GET_IS_BETSLIP_VALID',
  GET_IS_BETSLIP_EMPTY: 'GET_IS_BETSLIP_EMPTY',
  GET_CONSECUTIVE_DRAWS: 'GET_CONSECUTIVE_DRAWS',
  GET_MODE: 'GET_MODE',
  GET_IS_COMBO: 'GET_IS_COMBO',
  GET_WHEELS: 'GET_WHEELS',
  GET_WHEELS_LENGTH: 'GET_WHEELS_LENGTH',
  GET_WHEEL: 'GET_WHEEL',
  GET_MARKETS: 'GET_MARKETS',
  GET_QUICKPLAY_BETSLIP_DATA: 'GET_QUICKPLAY_BETSLIP_DATA',
};

const namespaceMapper = {
  SET_BETSLIP_ARRAY: `${MODULE_NAME}/${mutations.SET_BETSLIP_ARRAY}`,
  RESET_BETSLIP: `${MODULE_NAME}/${mutations.RESET_BETSLIP}`,
  RESET_ALL_BETSLIPS: `${MODULE_NAME}/${mutations.RESET_ALL_BETSLIPS}`,
  ACTION_RESET_BETSLIP: `${MODULE_NAME}/${actions.RESET_BETSLIP}`,
  ACTION_RESET_ALL_BETSLIPS: `${MODULE_NAME}/${actions.RESET_ALL_BETSLIPS}`,
  GET_SELECTED_BETSLIP: `${MODULE_NAME}/${getters.GET_SELECTED_BETSLIP}`,
  GET_TOTAL_COST: `${MODULE_NAME}/${getters.GET_TOTAL_COST}`,
  GET_IS_BETSLIP_VALID: `${MODULE_NAME}/${getters.GET_IS_BETSLIP_VALID}`,
  GET_IS_BETSLIP_EMPTY: `${MODULE_NAME}/${getters.GET_IS_BETSLIP_EMPTY}`,
};

export default {
  state,
  mutations,
  actions,
  getters,
  namespaceMapper,
};
