import moduleTypes from '../types';

const mutationTypes = {
  ADD_WHEEL: 'ADD_WHEEL',
  UPDATE_BETSLIP: 'UPDATE_BETSLIP',
  REMOVE_WHEEL: 'REMOVE_WHEEL',
  ADD_BETSLIP: 'ADD_BETSLIP',
  REMOVE_BETSLIP: 'REMOVE_BETSLIP',
  SET_REQUESTED_NUMBER: 'SET_REQUESTED_NUMBER',
  SET_COLUMN_NUMBER: 'SET_COLUMN_NUMBER',
  TOGGLE_QUICK_PICK: 'TOGGLE_QUICK_PICK',
  RESET_WHEEL: 'RESET_WHEEL',
  RESET_WHEELS: 'RESET_WHEELS',
  TOGGLE_GAME_TYPE: 'TOGGLE_GAME_TYPE',
  TOGGLE_MULTIPLIERS: 'TOGGLE_MULTIPLIERS',
  GENERATE_RANDOM_COLOR: 'GENERATE_RANDOM_COLOR',
  RESET_CATEGORY: 'RESET_CATEGORY',
  TOGGLE_BETSLIP_COMBO_MULTIPLIERS: 'TOGGLE_BETSLIP_COMBO_MULTIPLIERS',
  SET_BETSLIP_CONSECUTIVE_DRAWS: 'SET_BETSLIP_CONSECUTIVE_DRAWS',
  SET_QUICKPLAY_BETSLIP_DATA: 'SET_QUICKPLAY_BETSLIP_DATA',
  RESET_QUICKPLAY_BETSLIP_DATA: 'RESET_QUICKPLAY_BETSLIP_DATA',
  RESET_BETSLIPS: 'RESET_BETSLIPS',
  SET_SELECTED_BETSLIP_INDEX: 'SET_SELECTED_BETSLIP_INDEX',
  RESET_MARKETS: 'RESET_MARKETS',
  RESET_MARKETS_CATEGORY: 'RESET_MARKETS_CATEGORY',
  SET_MARKETS_NUMBER_ON_ANY_WHEEL: 'SET_MARKETS_NUMBER_ON_ANY_WHEEL',
  TOGGLE_MARKET_GAME_TYPE: 'TOGGLE_MARKET_GAME_TYPE',
  TOGGLE_MARKET_MULTIPLIERS: 'TOGGLE_MARKET_MULTIPLIERS',
};

const actionTypes = {
  ADD_WHEEL: 'ADD_WHEEL',
  UPDATE_BETSLIP: 'UPDATE_BETSLIP',
  REMOVE_WHEEL: 'REMOVE_WHEEL',
  ADD_BETSLIP: 'ADD_BETSLIP',
  REMOVE_BETSLIP: 'REMOVE_BETSLIP',
  SET_REQUESTED_NUMBER: 'SET_REQUESTED_NUMBER',
  SET_COLUMN_NUMBER: 'SET_COLUMN_NUMBER',
  QUICK_PICK_CLICKED: 'QUICK_PICK_CLICKED',
  GENERATE_RANDOM_COLOR: 'GENERATE_RANDOM_COLOR',
  RESET_WHEEL: 'RESET_WHEEL',
  RESET_WHEELS: 'RESET_WHEELS',
  TOGGLE_GAME_TYPE: 'TOGGLE_GAME_TYPE',
  TOGGLE_MULTIPLIERS: 'TOGGLE_MULTIPLIERS',
  RESET_CATEGORY: 'RESET_CATEGORY',
  TOGGLE_BETSLIP_COMBO_MULTIPLIERS: 'TOGGLE_BETSLIP_COMBO_MULTIPLIERS',
  SET_BETSLIP_CONSECUTIVE_DRAWS: 'SET_BETSLIP_CONSECUTIVE_DRAWS',
  SET_QUICKPLAY_BETSLIP_DATA: 'SET_QUICKPLAY_BETSLIP_DATA',
  RESET_QUICKPLAY_BETSLIP_DATA: 'RESET_QUICKPLAY_BETSLIP_DATA',
  RESET_BETSLIPS: 'RESET_BETSLIPS',
  SET_SELECTED_BETSLIP_INDEX: 'SET_SELECTED_BETSLIP_INDEX',
  RESET_MARKETS: 'RESET_MARKETS',
  RESET_MARKETS_CATEGORY: 'RESET_MARKETS_CATEGORY',
  SET_MARKETS_NUMBER_ON_ANY_WHEEL: 'SET_MARKETS_NUMBER_ON_ANY_WHEEL',
  TOGGLE_MARKET_GAME_TYPE: 'TOGGLE_MARKET_GAME_TYPE',
  TOGGLE_MARKET_MULTIPLIERS: 'TOGGLE_MARKET_MULTIPLIERS',
};

const getterTypes = {
  GET_ILOT_BETSLIP_ARRAY: 'GET_ILOT_BETSLIP_ARRAY',
  GET_ACTIVE_BETSLIP: 'GET_ACTIVE_BETSLIP',
  GET_WHEEL: 'GET_WHEEL',
  GET_CATEGORY_COST: 'GET_CATEGORY_COST',
  GET_WHEEL_COST: 'GET_WHEEL_COST',
  GET_WHEELS_LENGTH: 'GET_WHEELS_LENGTH',
  GET_BETSLIP_COST: 'GET_BETSLIP_COST',
  GET_BETSLIPS_COST: 'GET_BETSLIPS_COST',
  GET_CONSECUTIVE_DRAWS: 'GET_CONSECUTIVE_DRAWS',
  GET_SELECTED_BETSLIP: 'GET_SELECTED_BETSLIP',
  IS_BETSLIP_VALID: 'IS_BETSLIP_VALID',
  GET_BALANCE: 'GET_BALANCE',
  GET_MARKETS: 'GET_MARKETS',
  GET_MARKETS_COST: 'GET_MARKETS_COST',
  GET_WHEELS_COST: 'GET_WHEELS_COST',
};

const state = {
  BETSLIP_ARRAY: 'betslipArray',
  SELECTED_BETSLIP_INDEX: 'selectedBetslipIndex',
  QUICKPLAY_BETSLIP_DATA: 'quickplayBetslipData',
};

const namespaceMapper = {
  BETSLIP_COST: `${moduleTypes.POWERSPIN_GAME_STORE_MODULE}/${getterTypes.GET_BETSLIPS_COST}`,
  GET_CONSECUTIVE_DRAWS: `${moduleTypes.POWERSPIN_GAME_STORE_MODULE}/${getterTypes.GET_CONSECUTIVE_DRAWS}`,
  SET_CONSECUTIVE_DRAWS: `${moduleTypes.POWERSPIN_GAME_STORE_MODULE}/${actionTypes.SET_BETSLIP_CONSECUTIVE_DRAWS}`,
};

const types = {
  mutations: { ...mutationTypes },
  actions: { ...actionTypes },
  getters: { ...getterTypes },
  namespaceMapper: { ...namespaceMapper },
  state,
};

export default types;
