import moduleTypes from '../types/types';

const mutationTypes = {
  SET_BETSLIP: 'SET_BETSLIP',
  SET_SELECTED_BOARD_INDEX: 'SET_SELECTED_BOARD_INDEX',
  TOGGLE_NUMBER: 'TOGGLE_NUMBER',
  SET_SYSTEM: 'SET_SYSTEM',
  QUICK_PICK: 'QUICK_PICK',
  CLEAR_WORKING_BOARD: 'CLEAR_WORKING_BOARD',
  ADD_BOARD_TO_CART: 'ADD_BOARD_TO_CART',
  REMOVE_BOARD: 'REMOVE_BOARD',
  SHUFFLE_BOARD: 'SHUFFLE_BOARD',
  CLEAR_ALL_BOARDS: 'CLEAR_ALL_BOARDS',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
  ADD_MULTIPLE_RANDOM_BOARDS: 'ADD_MULTIPLE_RANDOM_BOARDS',
  ADD_ALL_20_TZOKER: 'ADD_ALL_20_TZOKER',
  COPY_BOARD_TO_WORKING: 'COPY_BOARD_TO_WORKING',
  UPDATE_BOARD_FROM_WORKING: 'UPDATE_BOARD_FROM_WORKING',
  RESET_BETSLIP: 'RESET_BETSLIP',
  SET_STATISTICS: 'SET_STATISTICS',
  SET_STATISTICS_SELECTION: 'SET_STATISTICS_SELECTION',
};

const actionTypes = {
  SET_BETSLIP: 'SET_BETSLIP',
  SET_SELECTED_BOARD_INDEX: 'SET_SELECTED_BOARD_INDEX',
  TOGGLE_NUMBER: 'TOGGLE_NUMBER',
  SET_SYSTEM: 'SET_SYSTEM',
  QUICK_PICK: 'QUICK_PICK',
  CLEAR_WORKING_BOARD: 'CLEAR_WORKING_BOARD',
  ADD_BOARD_TO_CART: 'ADD_BOARD_TO_CART',
  REMOVE_BOARD: 'REMOVE_BOARD',
  SHUFFLE_BOARD: 'SHUFFLE_BOARD',
  CLEAR_ALL_BOARDS: 'CLEAR_ALL_BOARDS',
  SET_CONSECUTIVE_DRAWS: 'SET_CONSECUTIVE_DRAWS',
  ADD_MULTIPLE_RANDOM_BOARDS: 'ADD_MULTIPLE_RANDOM_BOARDS',
  ADD_ALL_20_TZOKER: 'ADD_ALL_20_TZOKER',
  COPY_BOARD_TO_WORKING: 'COPY_BOARD_TO_WORKING',
  UPDATE_BOARD_FROM_WORKING: 'UPDATE_BOARD_FROM_WORKING',
  RESET_BETSLIP: 'RESET_BETSLIP',
  SET_STATISTICS_SELECTION: 'SET_STATISTICS_SELECTION',
  GET_STATISTICS: 'GET_STATISTICS',
};

const getterTypes = {
  GET_BETSLIP: 'GET_BETSLIP',
  GET_WORKING_BOARD: 'GET_WORKING_BOARD',
  GET_SELECTED_BOARD_INDEX: 'GET_SELECTED_BOARD_INDEX',
  GET_CART_BOARDS: 'GET_CART_BOARDS',
  GET_CONSECUTIVE_DRAWS: 'GET_CONSECUTIVE_DRAWS',
  GET_BOARD_COST: 'GET_BOARD_COST',
  GET_BETSLIP_COST: 'GET_BETSLIP_COST',
  GET_IS_BETSLIP_VALID: 'GET_IS_BETSLIP_VALID',
  GET_IS_BETSLIP_EMPTY: 'GET_IS_BETSLIP_EMPTY',
  GET_IS_WORKING_BOARD_VALID: 'GET_IS_WORKING_BOARD_VALID',
  GET_CAN_ADD_BOARDS: 'GET_CAN_ADD_BOARDS',
  GET_STATISTICS: 'GET_STATISTICS',
  GET_STATISTICS_SELECTION: 'GET_STATISTICS_SELECTION',
};

const namespaceMapper = {
  BETSLIP_COST: `${moduleTypes.TZOKER_GAME_STORE_MODULE}/${getterTypes.GET_BETSLIP_COST}`,
  GET_CONSECUTIVE_DRAWS: `${moduleTypes.TZOKER_GAME_STORE_MODULE}/${getterTypes.GET_CONSECUTIVE_DRAWS}`,
  SET_CONSECUTIVE_DRAWS: `${moduleTypes.TZOKER_GAME_STORE_MODULE}/${actionTypes.SET_CONSECUTIVE_DRAWS}`,
};

const types = {
  mutations: { ...mutationTypes },
  actions: { ...actionTypes },
  getters: { ...getterTypes },
  namespaceMapper: { ...namespaceMapper },
};

export default types;
