export default {
  GENERIC: {
    MODAL_ACTIVE: 'MODAL_ACTIVE',
  },
  OPEN: {
    INFO_SCROLLABLE: 'INFO_SCROLLABLE',
    HOW_TO_PLAY: 'HOW_TO_PLAY',
    DIALOG: 'DIALOG',
    SELECT_GAME: 'SELECT_GAME',
    WAGER_CAP: 'WAGER_CAP',
    INFO: 'INFO',
    OLD_TICKET_SCANNED: 'OLD_TICKET_SCANNED',
  },
  CLOSE: {
    ALL_MODALS: 'ALL_MODALS',
  },
};
