export const HALEventHandlerIDs = {
  PRINTER_EVENT: 1002,
  BCR_EVENT: 1003,
  BCR_DATA_EVENT: 1004,
  MESSAGING_EVENT: 1005,
  MESSAGE_ID: {
    BECOME_FOREGROUND: 3,
    BECOME_BACKGROUND: 4,
  },
  BARCODE_DATA: {
    VOUCHER_CODE_LENGTH: 26,
    L5_CODE_LENGTH: 36,
    L10_CODE_LENGTH: 57,
    VOUCHER_PROMO_CODE_LENGTH: 29,
    LOTTERY_CODE_LENGTH: 30,
    SCRATCH_CODE_LENGTH: 28,
    SPORTS_VOUCHER_PREFIX: 'V',
    SPORTS_TICKET_PREFIX: 'B',
    OPAP_BET_CARD: 'R1234',
  },
};
