export const HALToAppEventNames = {
  SHUTDOWN: 'shutDown',
  ENTER_BACKGROUND: 'enterBackground',
  ENTER_FOREGROUND: 'enterForeground',
  ENTER_FOREGROUND_IF_POSSIBLE: 'enterForegroundIfPossible',
  START_APP: 'startApp',
  PRINTER_STATUS: 'printerStatus',
  SCANNER_STATUS: 'scannerStatus',
  BCR_STATUS: 'bcrStatus',
  TC_STATUS: 'tcStatus',
  CDU_STATUS: 'cduStatus',
  BCR_DATA: 'bcrData',
  SCANNER_DATA: 'scannerData',
  TC_DATA: 'tcData',
  ACCESS_TOKEN_CHANGED: 'accessTokenChanged',
  ACCESS_TOKEB_DELETED: 'accessTokenDeleted',
  REFRESH_TOKEN_CHANGED: 'refreshTokenChanged',
  REFRESH_TOKEN_DELETED: 'refreshTokenDeleted',
  PUBLIC_KEY_CHANGED: 'publicKeyChanged',
  PUBLIC_KEY_DELETED: 'publicKeyDeleted',
  KEY_VALUE_CHANGED: 'keyValueChanged',
  KEY_VALUE_ZEROED: 'keyValueZeroed',
  ALL_VALUES_ZEROED: 'allValuesZeroed',
  CONFIG_CHANGED: 'configChanged',
};
