export const PrinterStatusTypes = {
  ACTIVE: 0,
  DISCONNECTED: 1,
  COVER_IS_OPEN: 2,
  PAPER_IS_EMPTY: 3,
  PAPER_JAM: 4,
  CUTTER_ERROR: 5,
  PAPER_EMPTY_BEFORE_PRINTING: 6,
  PAPER_EMPTY_AFTER_PRINTING: 7,
  PAPER_IS_NEAR_END: 8,
  GENERIC_ERROR: 9,
};
