import moduleTypes from '../types/types';

const actionTypes = {
  SET_CONFIGURATION: 'SET_CONFIGURATION',
  SET_VOUCHER: 'SET_VOUCHER',
  INITIALIZE_ASSETS: 'INITIALIZE_ASSETS',
  LOAD_ASSET: 'LOAD_ASSET',
  LOAD_SCREENSAVER_IDLE_TIME: 'LOAD_SCREENSAVER_IDLE_TIME',
  LOAD_SCREENSAVER_ENABLED: 'LOAD_SCREENSAVER_ENABLED',
  LOAD_FAQ_BOXES: 'LOAD_FAQ_BOXES',
  LOAD_FAQ_BOX: 'LOAD_FAQ_BOX',
  LOAD_MAIN_FAQ_SECTIONS: 'LOAD_MAIN_FAQ_SECTIONS',
  LOAD_DIGITAL_ASSISTANT_CONFIG: 'LOAD_DIGITAL_ASSISTANT_CONFIG',
  INITIALIZE_FAQ_DATA: 'INITIALIZE_FAQ_DATA',
  LOAD_CONFIGURATION: 'LOAD_CONFIGURATION',
  INIT_CONFIGURATION: 'INIT_CONFIGURATION',
};

const mutationTypes = {
  SET_CONFIGURATION: 'SET_CONFIGURATION',
  SET_VOUCHER: 'SET_VOUCHER',
  SET_CONFIG_LOADED: 'SET_CONFIG_LOADED',
  SET_ASSET_URL: 'SET_ASSET_URL',
  SET_BASE_URL: 'SET_BASE_URL',
  SET_SCREENSAVER_IDLE_TIME: 'LOAD_SCREENSAVER_IDLE_TIME',
  SET_SCREENSAVER_ENABLED: 'LOAD_SCREENSAVER_ENABLED',
  SET_FAQ_BOXES: 'SET_FAQ_BOXES',
  SET_CURRENT_FAQ_BOX: 'SET_CURRENT_FAQ_BOX',
  SET_MAIN_FAQ_SECTIONS: 'SET_MAIN_FAQ_SECTIONS',
};

const getterTypes = {
  GET_CONFIGURATION: 'GET_CONFIGURATION',
  IS_DEVELOPMENT_MODE: 'IS_DEVELOPMENT_MODE',
  GET_VOUCHER: 'GET_VOUCHER',
  GET_LIVE_DRAW_THEMES: 'GET_LIVE_DRAW_THEMES',
  GET_LIVE_DRAW_THEME_URL_DIRECTORY: 'GET_LIVE_DRAW_THEME_URL_DIRECTORY',
  GET_VOUCHER_MESSAGE: 'GET_VOUCHER_MESSAGE',
  GET_POWERSPIN_LIVE_DRAW_URLS: 'GET_POWERSPIN_LIVE_DRAW_URLS',
  GET_POWERSPIN_LAST_OLD_COLUMN_DRAW_TIME: 'GET_POWERSPIN_LAST_OLD_COLUMN_DRAW_TIME',
  GET_EUROJACKPOT_COLUMN_PRICE: 'GET_EUROJACKPOT_COLUMN_PRICE',
  GET_EUROJACKPOT_DRAW_DAYS: 'GET_EUROJACKPOT_DRAW_DAYS',
  GET_DRAW_API_HOST: 'GET_DRAW_API_HOST',
  GET_STATISTICS_API_HOST: 'GET_STATISTICS_API_HOST',
  GET_EJP_JACKPOT_API_CALL_INTERVAL: 'GET_EJP_JACKPOT_API_CALL_INTERVAL',
  GET_EJP_SALES_OPEN_TIME: 'GET_EJP_SALES_OPEN_TIME',
  IS_KINO_CLOSE_2_WIN_ENABLED: 'IS_KINO_CLOSE_2_WIN_ENABLED',
  IS_ADVERTISEMENT_ICON_HIDDEN: 'IS_ADVERTISEMENT_ICON_HIDDEN',
  GET_FIREBLAZE_COLUMN_PRICE: 'GET_FIREBLAZE_COLUMN_PRICE',
  GET_FIREBLAZE_LIVE_DRAW_URLS: 'GET_FIREBLAZE_LIVE_DRAW_URLS',
  GET_LIVE_DRAW_URLS: 'GET_LIVE_DRAW_URLS',
  GET_CONFIGURATION_ASSETS: 'GET_CONFIGURATION_ASSETS',
  GET_FAQ_BOXES: 'GET_FAQ_BOXES',
  GET_CURRENT_FAQ_BOX: 'GET_CURRENT_FAQ_BOX',
  GET_ASSET_URL: 'GET_ASSET_URL',
  GET_MAIN_FAQ_SECTIONS: 'GET_MAIN_FAQ_SECTIONS',
  GET_SCREENSAVER_IDLE_TIME: 'GET_SCREENSAVER_IDLE_TIME',
  IS_SCREEN_SAVER_ENABLED: 'IS_SCREENSAVER_ENABLED',
  GET_BRAND_NAME: 'GET_BRAND_NAME',
};

const namespaceMapper = {
  GET_EUROJACKPOT_COLUMN_PRICE: `${moduleTypes.CONFIGURATION_STORE_MODULE}/${getterTypes.GET_EUROJACKPOT_COLUMN_PRICE}`,
  GET_EUROJACKPOT_DRAW_DAYS: `${moduleTypes.CONFIGURATION_STORE_MODULE}/${getterTypes.GET_EUROJACKPOT_DRAW_DAYS}`,
  GET_DRAW_API_HOST: `${moduleTypes.CONFIGURATION_STORE_MODULE}/${getterTypes.GET_DRAW_API_HOST}`,
  GET_STATISTICS_API_HOST: `${moduleTypes.CONFIGURATION_STORE_MODULE}/${getterTypes.GET_STATISTICS_API_HOST}`,
  GET_EJP_JACKPOT_API_CALL_INTERVAL: `${moduleTypes.CONFIGURATION_STORE_MODULE}/${getterTypes.GET_EJP_JACKPOT_API_CALL_INTERVAL}`,
  GET_EJP_SALES_OPEN_TIME: `${moduleTypes.CONFIGURATION_STORE_MODULE}/${getterTypes.GET_EJP_SALES_OPEN_TIME}`,
  GET_FIREBLAZE_COLUMN_PRICE: `${moduleTypes.CONFIGURATION_STORE_MODULE}/${getterTypes.GET_FIREBLAZE_COLUMN_PRICE}`,
};

const types = {
  mutations: { ...mutationTypes },
  actions: { ...actionTypes },
  getters: { ...getterTypes },
  namespaceMapper: { ...namespaceMapper },
};

export default types;
